# Generated by Django 4.2.2 on 2023-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_title", models.CharField(max_length=100)),
                ("publication_text", models.CharField(max_length=500)),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
